// SPDX-License-Identifier: GPL-2.0
// AUTO-GENERATED by scripts/rule_compiler.py — DO NOT EDIT MANUALLY
// Source: iptables-save FORWARD chain
// Generated for: xdp-firewall gateway (ens19 ingress)

#include <linux/bpf.h>
#include <linux/pkt_cls.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include <linux/in.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

struct {
    __uint(type,        BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 2);
    __type(key,         __u32);
    __type(value,       __u64);
} fw_stats SEC(".maps");

static __always_inline void count(__u32 dropped) {
    __u64 *v = bpf_map_lookup_elem(&fw_stats, &dropped);
    if (v) __sync_fetch_and_add(v, 1);
}

SEC("tc")
int firewall_generated(struct __sk_buff *skb)
{
    void *data     = (void *)(long)skb->data;
    void *data_end = (void *)(long)skb->data_end;

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return TC_ACT_OK;
    if (eth->h_proto != bpf_htons(ETH_P_IP)) return TC_ACT_OK;

    struct iphdr *ip = (void *)(eth + 1);
    if ((void *)(ip + 1) > data_end) return TC_ACT_OK;

    __u32 src   = bpf_ntohl(ip->saddr);
    __u32 dst   = bpf_ntohl(ip->daddr);
    __u8  proto = ip->protocol;
    __u16 dport = 0;
    __u16 sport = 0;

    if (proto == IPPROTO_TCP) {
        struct tcphdr *tcp = (void *)ip + (ip->ihl * 4);
        if ((void *)(tcp + 1) > data_end) return TC_ACT_OK;
        dport = bpf_ntohs(tcp->dest);
        sport = bpf_ntohs(tcp->source);
    } else if (proto == IPPROTO_UDP) {
        struct udphdr *udp = (void *)ip + (ip->ihl * 4);
        if ((void *)(udp + 1) > data_end) return TC_ACT_OK;
        dport = bpf_ntohs(udp->dest);
        sport = bpf_ntohs(udp->source);
    }

    // ── Generated rules ───────────────────────────────────────────────────────
    // Rule 1: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': 80, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && dport == 80) { count(0); return TC_ACT_OK; }
    // Rule 2: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': None, 'sport': 80, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && sport == 80) { count(0); return TC_ACT_OK; }
    // Rule 3: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': 443, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && dport == 443) { count(0); return TC_ACT_OK; }
    // Rule 4: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': None, 'sport': 443, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && sport == 443) { count(0); return TC_ACT_OK; }
    // Rule 5: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': 5201, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && dport == 5201) { count(0); return TC_ACT_OK; }
    // Rule 6: {'proto': 'tcp', 'dst': None, 'src': None, 'dport': None, 'sport': 5201, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_TCP && sport == 5201) { count(0); return TC_ACT_OK; }
    // Rule 7: {'proto': 'icmp', 'dst': None, 'src': None, 'dport': None, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_ICMP) { count(0); return TC_ACT_OK; }
    // Rule 8: {'proto': 'udp', 'dst': None, 'src': None, 'dport': 53, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_UDP && dport == 53) { count(0); return TC_ACT_OK; }
    // Rule 9: {'proto': 'udp', 'dst': None, 'src': None, 'dport': None, 'sport': 53, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_UDP && sport == 53) { count(0); return TC_ACT_OK; }
    // Rule 10: {'proto': 'udp', 'dst': None, 'src': None, 'dport': 5001, 'sport': None, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_UDP && dport == 5001) { count(0); return TC_ACT_OK; }
    // Rule 11: {'proto': 'udp', 'dst': None, 'src': None, 'dport': None, 'sport': 5001, 'verdict': 'ACCEPT', 'type': 'filter'}
    if (proto == IPPROTO_UDP && sport == 5001) { count(0); return TC_ACT_OK; }

    // Default policy: DROP
    count(1); return TC_ACT_SHOT;
}

char _license[] SEC("license") = "GPL";
